fix( push.yml ): fixed no tags found

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -14,15 +14,16 @@ jobs:
         run: |
           git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
           git branch --remote --contains | grep origin/master
-      - name: Set VERSION variable from tag
+      - name: Set VERSION variable from tag or commit
         run: |
           git fetch --tags
-          # Attempt to get the most recent tag that looks like a semantic version
-          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
-          # If no tag found, or the tag doesn't match semantic versioning, use a default version plus commit hash
-          if [[ $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+          # Attempt to describe the current commit using the most recent tag
+          TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)
+          # Check if the describe command succeeded
+          if [[ $? -eq 0 && $TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
             VERSION=${TAG}
           else
+            # Fallback to a default version format with commit hash if describe fails
             COMMIT_HASH=$(git rev-parse --short HEAD)
             VERSION="0.0.0-$COMMIT_HASH"
           fi
